version: '3.1'
services:
  keycloak:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - variables.env
    volumes:
      - ./themes/gaze:/opt/jboss/keycloak/themes/gaze
